from os import system
import pygame
from random import shuffle
import time
nome1 = (str(input('Digite o primeiro nome: ')))
nome2 = (str(input('Digite o segundo nome: ')))
nome3 = (str(input('Digite o terceiro nome: ')))
nome4 = (str(input('Digite o quarto nome: ')))
nome5 = (str(input('Digite o quinto nome: ')))
nome6 = (str(input('Digite o sexto nome: ')))
lista = [nome1,nome2,nome3,nome4,nome5,nome6]
shuffle(lista)
print('A Ordem do Sorteio É.... ')
time.sleep(2)
print('...')
time.sleep(2)
print('hehehe')
time.sleep(2)
print('...')
pygame.init()
pygame.mixer.music.load('../assets/ex021.mp3')
pygame.mixer.music.play()
time.sleep(2)
print('...')
time.sleep(2)
print('...')
time.sleep(2)
print('...')
time.sleep(2)
print('...')
time.sleep(2)
print('aguenta aí está carregando')
time.sleep(2)
print('...')
time.sleep(2)
print('...')
time.sleep(2)
print('...')
time.sleep(2)
print('...')
time.sleep(2)
print('...')
time.sleep(2)
quest = str(input('Quer ver agora? '))
if quest == 'sim':
    time.sleep(2)
    pygame.mixer.music.stop()
    print(lista)
    system("pause")
else:
    time.sleep(2)
    print('...')
    time.sleep(2)
    print('hehehe')
    time.sleep(2)
    print('...')
    time.sleep(2)
    print('...')
    time.sleep(2)
    print('...')
    time.sleep(2)
    print('...')
    time.sleep(2)
    pygame.mixer.music.stop()
    print(lista)
    system("pause")